### PR TITLE
Update home.jsx

### PR DESCRIPTION
**Pull request by caojiele**
## What is the purpose of the change

#393 En pages should to add 'pic'.

## Brief changelog

`modify: site_config/home.jsx`

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by caojiele** [comment]
> It looks good to me, thanks for your contribution.

Hi, It looks like that did not resolve this problem, En pages not to add `user_chuangjinzhitou.png`. 
I think that build html in `/en-us/index.html`.

**Comment by lixiaojiee** [comment]
我看下

 原始邮件
发件人: Jlcao<notifications@github.com>
收件人: apache/dubbo-website<dubbo-website@noreply.github.com>
抄送: Xiaojie Li<lixiaojie@apache.org>; State change<state_change@noreply.github.com>
发送时间: 2019年6月12日(周三) 15:37
主题: Re: [apache/dubbo-website] Update home.jsx (#394)


It looks good to me, thanks for your contribution.

Hi, It looks like that did not resolve this problem, En pages not to add user_chuangjinzhitou.png.
I think that build html in /en-us/index.html.

**Comment by lixiaojiee** [comment]
hi 昨天网站已经重新构建并部署，你修改的内容已经生效

 原始邮件
发件人: Jlcao<notifications@github.com>
收件人: apache/dubbo-website<dubbo-website@noreply.github.com>
抄送: Xiaojie Li<lixiaojie@apache.org>; State change<state_change@noreply.github.com>
发送时间: 2019年6月12日(周三) 15:37
主题: Re: [apache/dubbo-website] Update home.jsx (#394)


It looks good to me, thanks for your contribution.

Hi, It looks like that did not resolve this problem, En pages not to add user_chuangjinzhitou.png.
I think that build html in /en-us/index.html.

**Comment by caojiele** [comment]
> hi 昨天网站已经重新构建并部署，你修改的内容已经生效 原始邮件 发件人: Jlcao<notifications@github.com> 收件人: apache/dubbo-website<dubbo-website@noreply.github.com> 抄送: Xiaojie Li<lixiaojie@apache.org>; State change<state_change@noreply.github.com> 发送时间: 2019年6月12日(周三) 15:37 主题: Re: [apache/dubbo-website] Update home.jsx (#394) It looks good to me, thanks for your contribution. Hi, It looks like that did not resolve this problem, En pages not to add user_chuangjinzhitou.png. I think that build html in /en-us/index.html. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGBXYEVMB4TS6JIEILTP2CRTHA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXPQYOA%23issuecomment-501156920&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466178615&sdata=4xn6ywxRi8lP7qE%2F301T5ybXoH3ZJveXacEtiuyNXSk%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGEEALTOCW4ANPOAHXDP2CRTHANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466188620&sdata=tuD6A9Vr8LEYupZYwHTOXzQDf%2BOEtNsHuFrzmknKLYo%3D&reserved=0>.

OK，但是我还有个问题。这个添加公司logo和最后部署构建，除了我改动的地方，还有哪些文件需要改动？

**Comment by lixiaojiee** [comment]
没有了，保证/img包下有logo图片的情况下，在home.jsx里填上对应的路径即可

 原始邮件
发件人: 天璇<notifications@github.com>
收件人: apache/dubbo-website<dubbo-website@noreply.github.com>
抄送: Xiaojie Li<lixiaojie@apache.org>; State change<state_change@noreply.github.com>
发送时间: 2019年6月14日(周五) 09:52
主题: Re: [apache/dubbo-website] Update home.jsx (#394)


hi 昨天网站已经重新构建并部署，你修改的内容已经生效 原始邮件 发件人: Jlcaonotifications@github.com<mailto:notifications@github.com> 收件人: apache/dubbo-websitedubbo-website@noreply.github.com<mailto:dubbo-website@noreply.github.com> 抄送: Xiaojie Lilixiaojie@apache.org<mailto:lixiaojie@apache.org>; State changestate_change@noreply.github.com<mailto:state_change@noreply.github.com> 发送时间: 2019年6月12日(周三) 15:37 主题: Re: [apache/dubbo-website] Update home.jsx (#394<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237066351&sdata=ijZWr9T3vsh68yQOfGtYeDVWCXBA2iD93GwvTVsn7G4%3D&reserved=0>) It looks good to me, thanks for your contribution. Hi, It looks like that did not resolve this problem, En pages not to add user_chuangjinzhitou.png. I think that build html in /en-us/index.html. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHubhttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGBXYEVMB4TS6JIEILTP2CRTHA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXPQYOA%23issuecomment-501156920&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466178615&sdata=4xn6ywxRi8lP7qE%2F301T5ybXoH3ZJveXacEtiuyNXSk%3D&reserved=0<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGBXYEVMB4TS6JIEILTP2CRTHA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXPQYOA%23issuecomment-501156920&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237086367&sdata=d0%2FPbSsCxqNaN6lo76QvA8unavjCrCPMO9R0tx43l3A%3D&reserved=0>, or mute the threadhttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGEEALTOCW4ANPOAHXDP2CRTHANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466188620&sdata=tuD6A9Vr8LEYupZYwHTOXzQDf%2BOEtNsHuFrzmknKLYo%3D&reserved=0<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGEEALTOCW4ANPOAHXDP2CRTHANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237096378&sdata=A3o60M%2F90%2B4hNurRYv9bVEio6KoQD%2Fh32MNNm3JMMjU%3D&reserved=0>.

OK，但是我还有个问题。这个添加公司logo和最后部署构建，除了我改动的地方，还有哪些文件需要改动？

**Comment by caojiele** [comment]
> 没有了，保证/img包下有logo图片的情况下，在home.jsx里填上对应的路径即可 原始邮件 发件人: 天璇<notifications@github.com> 收件人: apache/dubbo-website<dubbo-website@noreply.github.com> 抄送: Xiaojie Li<lixiaojie@apache.org>; State change<state_change@noreply.github.com> 发送时间: 2019年6月14日(周五) 09:52 主题: Re: [apache/dubbo-website] Update home.jsx (#394) hi 昨天网站已经重新构建并部署，你修改的内容已经生效 原始邮件 发件人: Jlcaonotifications@github.com<mailto:notifications@github.com> 收件人: apache/dubbo-websitedubbo-website@noreply.github.com<mailto:dubbo-website@noreply.github.com> 抄送: Xiaojie Lilixiaojie@apache.org<mailto:lixiaojie@apache.org>; State changestate_change@noreply.github.com<mailto:state_change@noreply.github.com> 发送时间: 2019年6月12日(周三) 15:37 主题: Re: [apache/dubbo-website] Update home.jsx (#394<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237066351&sdata=ijZWr9T3vsh68yQOfGtYeDVWCXBA2iD93GwvTVsn7G4%3D&reserved=0>) It looks good to me, thanks for your contribution. Hi, It looks like that did not resolve this problem, En pages not to add user_chuangjinzhitou.png. I think that build html in /en-us/index.html. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHubhttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGBXYEVMB4TS6JIEILTP2CRTHA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXPQYOA%23issuecomment-501156920&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466178615&sdata=4xn6ywxRi8lP7qE%2F301T5ybXoH3ZJveXacEtiuyNXSk%3D&reserved=0<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGBXYEVMB4TS6JIEILTP2CRTHA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXPQYOA%23issuecomment-501156920&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237086367&sdata=d0%2FPbSsCxqNaN6lo76QvA8unavjCrCPMO9R0tx43l3A%3D&reserved=0>, or mute the threadhttps://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGEEALTOCW4ANPOAHXDP2CRTHANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf8d5030c23ce45b12f6808d6ef08d08b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959218466188620&sdata=tuD6A9Vr8LEYupZYwHTOXzQDf%2BOEtNsHuFrzmknKLYo%3D&reserved=0<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGEEALTOCW4ANPOAHXDP2CRTHANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237096378&sdata=A3o60M%2F90%2B4hNurRYv9bVEio6KoQD%2Fh32MNNm3JMMjU%3D&reserved=0>. OK，但是我还有个问题。这个添加公司logo和最后部署构建，除了我改动的地方，还有哪些文件需要改动？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo-website%2Fpull%2F394%3Femail_source%3Dnotifications%26email_token%3DAIJZIGE4JXFI4VVKT3IXLQLP2L2UBA5CNFSM4HSF64H2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVPSMY%23issuecomment-501938483&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237106384&sdata=Z9u9wzRE0aVtnr6wAapOlmejknLcUoJySp%2Bdtw4g3Pw%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIJZIGHOD4QH46QKLXB6ZDDP2L2UBANCNFSM4HSF64HQ&data=02%7C01%7C%7Cf93dca48c6e4483a013e08d6f06ae5bb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636960739237116395&sdata=nQmoVXDz4QimfbY9lm%2F9XDq7WxyA%2F7O%2Frgf5tbghJ00%3D&reserved=0>.

这就很奇怪，我在Nacos官网也是这样添加，但是它不会像Dubbo自动生成。

**Pull request merged**
