### PR TITLE
Fix dead links and typo

### PR DESCRIPTION
**Pull request by caojiele**
## What is the purpose of the change

#399 , Fix dead links and typo.

## Brief changelog

`modify: docs/en-us/developers/committer-guide/apache-dubbo-page_dev.md `
`modify: docs/zh-cn/developers/committer-guide/apache-dubbo-page_dev.md`

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
Thanks !

**Comment by caojiele** [comment]
> Thanks !

Hi, relevant documents(apache-dubbo-page_dev.html , apache-dubbo-page_dev.json) need to submit?

**Comment by htynkn** [comment]
No, those html files are generated. CI job will handle it.

Just checked, changes are deployed to server. you can refer to page:
http://dubbo.apache.org/zh-cn/docs/developers/committer-guide/apache-dubbo-page_dev.html
http://dubbo.apache.org/en-us/docs/developers/committer-guide/apache-dubbo-page_dev.html

**Comment by caojiele** [comment]
> No, those html files are generated. CI job will handle it.
> 
> Just checked, changes are deployed to server. you can refer to page:
> http://dubbo.apache.org/zh-cn/docs/developers/committer-guide/apache-dubbo-page_dev.html
> http://dubbo.apache.org/en-us/docs/developers/committer-guide/apache-dubbo-page_dev.html

All right. 👍

**Pull request merged**
