### PR TITLE
fix: DUBBO_DUBBO_IP_TO_REGISTRY

### PR DESCRIPTION
**Pull request by nisiyong**
* replace `DUBBO_DUBBO_PORT_TO_BIND` with `DUBBO_DUBBO_IP_TO_REGISTRY`
* format the document

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Please do not modify doscy submodule

**Comment by nisiyong** [comment]
> Please do not modify doscy submodule

Oops! It has been reverted.

**Comment by nisiyong** [comment]
@AlbumenJ It was fixed, please take a look.

**Review by AlbumenJ — APPROVED** [review]
LGTM

**Pull request merged**
