### PR TITLE
Add doc metrics chap.1

### PR DESCRIPTION
**Pull request by namelessssssssssss**
添加指标模块的源码分析文档，将分为4章：
* 指标样本的收集与存储
* 指标收集器的指标采集流程
* 指标监听注册梳理
* 指标转换导出

### CODE REVIEW

**Comment by namelessssssssssss** [comment]
@songxiaosheng @AlbumenJ  PTAL ;)

**Comment by songxiaosheng** [comment]
@AlbumenJ  the error is : "curl 127.0.0.1:2222 "?
image

before the error as follow because the code is old.
image

**Comment by AlbumenJ** [comment]
> Details

Make `curl 127.0.0.1:22222` as code. Or it would be a hyper link.

**Comment by AlbumenJ** [comment]
> > Details
> 
> Make `curl 127.0.0.1:22222` as code. Or it would be a hyper link.

I have fix it.

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
