### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by sofkyle**
## What is the purpose of the change

fix some link errors.

## Brief changelog

/docs/zh-cn/user/versions/version-270.md

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Test your code locally by running `docsite start`, and make sure it works as expected.
- [x] Make sure no files under build directory is added.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
I just noticed that you also change the suffix from md to html. I think docsite should able to handle it. refer to https://raw.githubusercontent.com/apache/dubbo-website/master/docs/en-us/admin/serviceTest.md as example

**Comment by htynkn** [comment]
Thanks for your contribution

**Comment by sofkyle** [comment]
@htynkn Your way may not works. I did an experiment. I change the url in two ways by chrome developer tool .

My experiment is as follows: 

1、Change the value of href to "/zh-cn/docs/user/demos/routing-rule.**md**", then click the link "路由规则". The browser shows "Not Found" error.

2、Change the value of href to "/zh-cn/docs/user/demos/routing-rule.**html**", then click the link "路由规则". The browser redirect successfully.

**Comment by htynkn** [comment]
@sofkyle thanks so much for verifying this.
You are right, it must be html. 

I already fix it in master branch. This change will deploy to website by CI later

**Pull request merged**
