### PR TITLE
:memo:Perfection of observability documents

### PR DESCRIPTION
**Pull request by songxiaosheng**

### CODE REVIEW

**Comment by AlbumenJ** [comment]
```
zh-cn/overview/core-features/observability/index.html
  href blank --- zh-cn/overview/core-features/observability/index.html --> 
  href blank --- zh-cn/overview/core-features/observability/index.html --> 
  href blank --- zh-cn/overview/core-features/observability/index.html --> 
========================================================================

```

**Comment by AlbumenJ** [comment]
image

**Comment by songxiaosheng** [comment]
> image
> 
please wait

**Comment by chickenlj** [comment]
Close for outdated.

**Pull request closed without merging**
